# Spring uygulamas?n?n çal??aca?? port (Genelde 8080'dir, çak??ma olmamas? için 8081 yapabiliriz)
server.port=8081

# PostgreSQL veritaban? ba?lant? adresi (modunubul_db ad?nda bir veritaban? kuraca??z)
spring.datasource.url=jdbc:postgresql://localhost:5432/modunubul_db

# Veritaban? kullan?c? ad?
spring.datasource.username=postgres

# Veritaban? ?ifresi (Kendi ?ifreni buraya yazacaks?n)
spring.datasource.password=1234

# Hibernate ayarlar?: Entity s?n?flar?na bakarak tablolar? otomatik olu?turur/günceller
spring.jpa.hibernate.ddl-auto=update

# Arka planda çal??an SQL sorgular?n? konsola yazd?r?r (Geli?tirme a?amas?nda çok i?imize yarar)
spring.jpa.show-sql=true